name: Publish

on:
  release:
    types:
      - created

jobs:
  Release:
    runs-on: ubuntu-latest
    container: node:10.18-jessie
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          path: painandsuffering/repo

      - name: Install Zip
        run: sudo apt install zip unzip
      
      - name: Archive Repository
        run: zip -r ASW-${{ github.ref }}.rwmod painandsuffering/repo

      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/release/ASW-${{ github.ref }}.rwmod
          asset_name: ASW-${{ github.ref }}.rwmod
          tag: ${{ github.ref }}
          overwrite: true
