name: Publish

on:
  release:
    types:
      - created

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Zips code
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: '${{ github.ref }}.rwmod'
          exclusions: '*.git* /*node_modules/* .editorconfig'
          command: "mkdir -p build/release"

      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/release/ASW-${{ github.ref }}.rwmod
          asset_name: ASW-${{ github.ref }}.rwmod
          tag: ${{ github.ref }}
          overwrite: true
