name: Package
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'ASW-$GITHUB_REF_NAME.rwmod'
        exclusions: '*.git*'
        path: build/zip/
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "ASW-$GITHUB_REF_NAME.rwmod"
        token: ${{ secrets.GITHUB_TOKEN }}