name: Package
on: 
  push:
    tags:
    - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: '${{ github.ref }}.zip'
        exclusions: '*.git*'
    - name: Rename file 
      run: mv ${{ github.ref }}.zip ${{ github.ref }}.rwmod
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false  
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ github.ref }}.rwmod
        asset_name: ${{ github.ref }}.rwmod
        tag: ${{ github.ref }}
        overwrite: true